export * from './education/education.component'
export * from './experience/experience.component'
export * from './index/index.component'
export * from './profile/profile.component'
export * from './projects/projects.component'